FROM {{parent}}:{{parent_version}}

RUN cd /opt/ && \
    wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm && \
    yum localinstall jdk-8u102-linux-x64.rpm && \
    rm jdk-8u102-linux-x64.rpm

ENV JAVA_HOME /usr/java/jdk1.8.0_102
ENV PATH ${PATH}:${JAVA_HOME}/bin
